### PR TITLE
Remove mergify.yml

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by jwendell — CHANGES_REQUESTED** [review]
We don't use mergify anymore. We use prow and tide now. Feel free to remove this file.

**Comment by luksa** [comment]
Thanks. Does it honor the Don't squash label?

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
> Thanks. Does it honor the Don't squash label?

Yes. Just FIY: https://github.com/maistra/test-infra/blob/main/prow/config/tide.yaml#L7

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
